"use strict";

module.exports.BASE_URL = "/v1";

module.exports.ALBUM = (albumID) => `/albums/${albumID}`;
module.exports.ALBUM_TRACK = (albumID) => `/albums/${albumID}/tracks`;
module.exports.ALBUMS = "/albums";
module.exports.ARTIST = (artistID) => `/artists/${artistID}`;
module.exports.ARTIST_ALBUM = (artistID) => `/artists/${artistID}/albums`;
module.exports.ARTIST_TOP_TRACKS = (artistID) => `/artists/${artistID}/top-tracks`;
module.exports.ARTIST_RELATED_ARTISTS = (artistID) => `/artists/${artistID}/related-artists`;
module.exports.ARTISTS = "/artists";
module.exports.AUDIO_ANALYSI = (trackID) => `/audio-analysis/${trackID}`;
module.exports.AUDIO_FEATURE = (trackID) => `/audio-features/${trackID}`;
module.exports.AUDIO_FEATURES = "/audio-features";
module.exports.BROWSE_CATEGORIE = (categoryID) => `/browse/categories/${categoryID}`;
module.exports.BROWSE_CATEGORIE_PLAYLISTS = (categoryID) => `/browse/categories/${categoryID}/playlists`;
module.exports.BROWSE_CATEGORIES = "/browse/categories";
module.exports.BROWSE_FEATURED_PLAYLISTS = "/browse/featured-playlists";
module.exports.BROWSE_NEW_RELEASES = "/browse/new-releases";
module.exports.ME = "/me";
module.exports.ME_ALBUMS = "/me/albums";
module.exports.ME_ALBUMS_CONTAINS = "/me/albums/contains";
module.exports.ME_TRACKS = "/me/tracks";
module.exports.ME_TRACKS_CONTAINS = "/me/tracks/contains";
module.exports.ME_TOP = (type) => `/me/top/${type}`;
module.exports.ME_PLAYER_DEVICES = "/me/player/devices";
module.exports.ME_PLAYER = "/me/player";
module.exports.ME_PLAYER_RECENTLY_PLAYED = "/me/player/recently-played";
module.exports.ME_PLAYER_CURRENTLY_PLAYING = "/me/player/currently-playing";
module.exports.ME_PLAYLISTS = "/me/playlists";
module.exports.ME_PLAYLIST = (playlistID) => `/playlists/${playlistID}`;
module.exports.ME_PLAYLIST_IMAGES = (playlistID) => `/playlists/${playlistID}/images`;
module.exports.ME_PLAYLIST_TRACKS = (playlistID) => `/playlists/${playlistID}/tracks`;
module.exports.ME_USER_PLAYLISTS = (userID) => `/users/${userID}/playlists`;
module.exports.RECOMMENDATIONS = "/recommendations";
module.exports.TRACK = (trackID) => `/tracks/${trackID}`;
module.exports.TRACKS = "/tracks";
module.exports.USER = (userID) => `/users/${userID}`;